### PR TITLE
build-docker creates a scratch Docker image

### PR DESCRIPTION
**Pull request by jkt628**
Usage:
docker run -i --rm coreos/ct <ignition.yaml >ignition.json

### CODE REVIEW

**Comment by dgonyeo** [comment]
My googling doesn't appear to be pulling up this answer quickly, what's the difference between `Dockerfile` and `Dockerfile.build`? One appears to rely on the binary built outside of docker, but when is one used over the other?

Aside from that, looks fine.

**Comment by jkt628** [comment]
1. build-docker uses Dockerfile.build to create a container that uses the build script to create the executable.
2. then build-docker uses that executable and Dockerfile to create a tiny "from scratch" image.

**Comment by dgonyeo** [comment]
I think I would prefer you to do that, otherwise new users might try to just `docker build` when they see a `Dockerfile`, and the resulting image wouldn't work since libc would be missing (assuming they've already built ct).

**Comment by jkt628** [comment]
and there you go....

**Pull request merged**
